### ISSUE TITLE
Big thanks

### ISSUE THREAD

**Issue by matb33** [bennadel/AngularJS-Routing#3]
Ben, thanks for this. I spent hours with vanilla routing, and more hours with ui-router... nothing did the trick. Parent views getting re-rendered when only the child views should have been affected was the crux of the problem, which your implementation solved.

I ended up doing a bit of abstraction but am not yet sure if it was wise -- only time will tell!

A small note: as of Angular 1.2.0rc1, in the `$routeChangeSuccess` callback, getting the action can be done like so:

``` javascript
var action = $route.current.$$route && $route.current.$$route.action;
```

**Comment by bennadel** [comment]
@matb33 Hey man, thanks for the note. Sorry for not responding sooner. I commit a lot to GitHub, but I don't actually know that much about notifications. I only found this one because I was curious what that "blue dot" at the top of the page meant :D I'll know for next time. Cheers!
